### ISSUE TITLE
Do SPARQL tutorials

### ISSUE THREAD

**Issue by gannonprudhomme** [gannonprudhomme/CSCE-482-KNOW-backend#16]
To get as caught up as I am with RDF parsing I would recommend:

In python use rdflib to parse william blake's RDF file. Don't forget to request the turtle format. Print all the triples in the graph either turtle format or n-triples format. Here's their documentation. https://rdflib.readthedocs.io/en/stable/

Read [Wikidata's SPARQL tutorial](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial) and then do a few sample queries on their SPARQL endpoint. You shouldn't need to read the entire tutorial as it's quite long and goes into advanced topics but I would read at least to the Qualifiers section.

Try using their SPARQL endpoint through a GET request in Python.

**Comment by nikthom** [comment]
To get as caught up as I am with RDF parsing I would recommend:

In python use rdflib to parse william blake's RDF file. Don't forget to request the turtle format. Print all the triples in the graph either turtle format or n-triples format.

Read Wikidata's SPARQL tutorial( https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial ) and then do a few sample queries on their SPARQL endpoint. You shouldn't need to read the entire tutorial as it's quite long and goes into advanced topics but I would read at least to the Qualifiers section.

Try using their SPARQL endpoint through an get request in Python.

**Comment by gannonprudhomme** [comment]
@nikthom Can you update it with specific links? E.g. WikiData's SPARQL tutorial and SPARQL endpoint (if it's not included in the tutorial). Note that you can just edit the description, rather than adding it as a comment.

You can embed links in markdown like: `[text](link)`

**Comment by nikthom** [comment]
@gannonprudhomme okay what is the description field? Also the sparql tutorial is the first result on Google and the tutorial links their endpoint too.

**Comment by gannonprudhomme** [comment]
> @gannonprudhomme okay what is the description field

The description of the issue
