### ISSUE TITLE
Setup RDF Parser

### ISSUE THREAD

**Issue by NatalieBurks** [gannonprudhomme/CSCE-482-KNOW-backend#6]
We need to setup the outline for the rdf parser, so when can easily start adding SPARQL queries and we have an easy place to execute them.

Needs to:
- Setup folder to put SPARQL files in
- Have a dynamic way / module for loading and executing SPARQL queries
- Have a consistent way for handling the results of the queries

### Folder layout:

- SPARQL queries
  - wikidata
    - get_entity_type.sparql
    - person
       - get_name.sparql
    - work_of_art
       - book / journal
         - get_publish_date.sparql
         - get_author.sparql
  - viaf
     - get_entity_type.sparql

### SPARQL Class hierarchy

- Person
  - get_name
  - get_something
- WorkOfArt
  - Painting
     - get_author
  - LiteraryWork
     - get_author

Then each one would be implemented by Viaf and WikiData accordingly

**Comment by gannonprudhomme** [comment]
Updated to "Setup RDF parser" & added description, as I'm assuming you didn't want to plan on making this an epic (with sub-issues)
